---
- name: Get kubectl installed version
  ansible.builtin.command: "kubectl version --client=true"
  register: kubectl_check_info
  changed_when: false
  failed_when: false

- name: Get the specific kubectl version associated to stable
  when: kubectl_version == "stable"
  block:
    - name: Retreive the specific kubectl version
      ansible.builtin.uri:
        url: "{{ kubectl_stable_version_url }}"
        return_content: true
        status_code: 200
      register: kubectl_stable_version_response
    - name: Set the kubectl specific version
      ansible.builtin.set_fact:
        kubectl_derived_version: "{{ kubectl_stable_version_response.content }}"

- name: Check if kubectl is already installed with the correct version
  ansible.builtin.set_fact:
    kubectl_already_installed: "{{ kubectl_check_info is defined and kubectl_check_info.stdout is ansible.builtin.search(kubectl_derived_version) }}"

- name: Display info when kubectl is already installed with the correct version
  ansible.builtin.debug:
    msg: "kubectl is already installed with the correct version : {{ kubectl_derived_version }}"
  when: kubectl_already_installed

- name: Install kubectl
  ansible.builtin.include_tasks: "install-kubectl.yml"
  when: not kubectl_already_installed
