---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    should_verify_kubectl_checksum: true

  tasks:
    - name: Include willbrid.kubectl_installer
      ansible.builtin.include_role:
        name: "willbrid.kubectl_installer"
